# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stt_pb2 as stt__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SttStub:
    """Bidirectional-streaming STT service hosted by the Python STT worker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.stream_stream(
                '/marceline.stt.Stt/Transcribe',
                request_serializer=stt__pb2.SttRequest.SerializeToString,
                response_deserializer=stt__pb2.SttResponse.FromString,
                _registered_method=True)


class SttServicer:
    """Bidirectional-streaming STT service hosted by the Python STT worker.
    """

    def Transcribe(self, request_iterator, context):
        """Streams audio in, streams transcripts out. The client interleaves
        `Cancel` messages on the request stream to stop an in-flight
        transcription cooperatively (§2.5.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=stt__pb2.SttRequest.FromString,
                    response_serializer=stt__pb2.SttResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marceline.stt.Stt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marceline.stt.Stt', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stt:
    """Bidirectional-streaming STT service hosted by the Python STT worker.
    """

    @staticmethod
    def Transcribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/marceline.stt.Stt/Transcribe',
            stt__pb2.SttRequest.SerializeToString,
            stt__pb2.SttResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
