# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\rmarceline.stt\x1a\x0c\x63ommon.proto\"r\n\nSttRequest\x12-\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x1c.marceline.common.AudioChunkH\x00\x12*\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x18.marceline.common.CancelH\x00\x42\t\n\x07payload\"_\n\x0bSttResponse\x12\x11\n\x07partial\x18\x01 \x01(\tH\x00\x12/\n\x05\x66inal\x18\x02 \x01(\x0b\x32\x1e.marceline.stt.FinalTranscriptH\x00\x42\x0c\n\ntranscript\"3\n\x0f\x46inalTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32N\n\x03Stt\x12G\n\nTranscribe\x12\x19.marceline.stt.SttRequest\x1a\x1a.marceline.stt.SttResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STTREQUEST']._serialized_start=42
  _globals['_STTREQUEST']._serialized_end=156
  _globals['_STTRESPONSE']._serialized_start=158
  _globals['_STTRESPONSE']._serialized_end=253
  _globals['_FINALTRANSCRIPT']._serialized_start=255
  _globals['_FINALTRANSCRIPT']._serialized_end=306
  _globals['_STT']._serialized_start=308
  _globals['_STT']._serialized_end=386
# @@protoc_insertion_point(module_scope)
