# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\rmarceline.tts\x1a\x0c\x63ommon.proto\"S\n\nTtsRequest\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12*\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x18.marceline.common.CancelH\x00\x42\t\n\x07payload\":\n\x0bTtsResponse\x12+\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x1c.marceline.common.AudioChunk2N\n\x03Tts\x12G\n\nSynthesize\x12\x19.marceline.tts.TtsRequest\x1a\x1a.marceline.tts.TtsResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=42
  _globals['_TTSREQUEST']._serialized_end=125
  _globals['_TTSRESPONSE']._serialized_start=127
  _globals['_TTSRESPONSE']._serialized_end=185
  _globals['_TTS']._serialized_start=187
  _globals['_TTS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
