# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tts_pb2 as tts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TtsStub:
    """Bidirectional-streaming TTS service hosted by the Python TTS worker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.stream_stream(
                '/marceline.tts.Tts/Synthesize',
                request_serializer=tts__pb2.TtsRequest.SerializeToString,
                response_deserializer=tts__pb2.TtsResponse.FromString,
                _registered_method=True)


class TtsServicer:
    """Bidirectional-streaming TTS service hosted by the Python TTS worker.
    """

    def Synthesize(self, request_iterator, context):
        """Streams already-segmented text in (sentence-chunking is the caller's
        job, §5.3), streams audio chunks out. The client interleaves `Cancel`
        messages on the request stream to stop in-flight synthesis
        cooperatively (§2.5.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tts__pb2.TtsRequest.FromString,
                    response_serializer=tts__pb2.TtsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marceline.tts.Tts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marceline.tts.Tts', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tts:
    """Bidirectional-streaming TTS service hosted by the Python TTS worker.
    """

    @staticmethod
    def Synthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/marceline.tts.Tts/Synthesize',
            tts__pb2.TtsRequest.SerializeToString,
            tts__pb2.TtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
